language: r
r: bioc-devel

env:
  global:
    - secure: "YhKfqZ1Ux/e2DvnfIcyJoI58Kz+qkAEML+9OPTpTaJ1RwBzC9drfN24NBrzds79zj+jI/9xqsZjlBm6dREXtoT/mALQEkt1Vwb52z2kTHnZeTxxwH2nNn4qa+OKqcHa+y69i4LDaClwffPCl43y7H9oy+sciYhBSbRey13+vXNXQayHR1AUGAHsLt54X+evxsL271aa7kVOkrePpht7wHYtsKAoPyKqFOfcD1/Q+hWehDi5Y6jnGZxr9mLaH8rul93ygQ2eZtWN2znjDa2346chXo8cYOVorgbWLYjPmaOvEyXBjB5570HcaF4AK0Qjup1UeRK8n4sYxYma9JDIKTesqEAXeTjhIVxMQDMSWejBJdkj24JPXoQjWRt57dnuBUwHFH3uhIB8So6I5gEAI/vZV4PSHX0ciDcfmQdAtXO0lH1Y7OStiTTmqi81WK8D1oyLfEqsQipO6HIFtFz+DNXbvSHrT9Bo2qNIfIuUdQjMl/goCYklC4OyJPiom5DABj3eSPvDYZHH+1tiTUoPlAsKxxj74QqTIbg+HYFTtvSEN8PG7+uZUCuu8ZU+OJhbxaUlDqSH6nPrYRebzgIv4ChudqBctwZN//OV+PCLAsMBiZQ0PG6WL0YAsLFOo03XvTDbWp8KTMUA61T4sTDEoXpJUClFvc7ftEX8XoSgcX+o="

cache:
  packages: true
  directories:
  - docs
  - $TRAVIS_BUILD_DIR/_bookdown_files

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

